### ISSUE TITLE
Typo on Chap3 tslint.json

### ISSUE THREAD

**Issue by ramonberrutti** [carlrip/LearnReact17WithTypeScript#1]
Hi, I'm reading your book on MAPT (Packtpub) and found an error:

there is a extra colon (,) on the rules option:

```
  "rules": {
    "ordered-imports": false,
    "object-literal-sort-keys": false,
    "no-debugger": false,
    "no-console": false,
  },
```

need to be: 

```
  "rules": {
    "ordered-imports": false,
    "object-literal-sort-keys": false,
    "no-debugger": false,
    "no-console": false
  },
```

sorry if here don't is the right place for this.

**Comment by carlrip** [comment]
Thanks for letting me know ramonberrutti. Hope you are enjoying the book!

**Comment by denis-n** [comment]
It's not an issue, it's a valid ES6/TypeScript and probably javascript too.

I think it's just what a formatter liker Prettier does.
